version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: EST
  open-pull-requests-limit: 10
  reviewers:
  - ssmirr
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: systeminformation
    versions:
    - 4.31.1
    - 5.3.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: dockerode
    versions:
    - 3.2.1
